// Alloy backend — relational structure only.
//
// Owns ACC-TENANT-001 (relational-invariant). Balance and sync are NOT
// re-checked here. Emits real Alloy 6 source with the TenantIsolation assertion
// and a bounded `check`. The verifier runs the Alloy Analyzer when present;
// otherwise dspec's finite-scope relational enumerator (relational-check.mjs)
// checks the same bounded universe and records `bounded` evidence with the scope.

export function emitAlloy(ir) {
  const rule = ir.rules.find((r) => r.id === "ACC-TENANT-001");
  const text = `// GENERATED by dspec from examples/accounting-core.pkl
// Rule: ACC-TENANT-001 (relational-invariant) — primary backend: Alloy

module accounting_tenant

sig Tenant {}

sig AccountingPeriod { owner : one Tenant }

sig JournalEntry {
  owner  : one Tenant,
  period : one AccountingPeriod
}

sig JournalLine {
  owner : one Tenant,
  entry : one JournalEntry
}

sig ExternalSyncRecord {
  owner : one Tenant,
  entry : one JournalEntry
}

// The scoping the implementation enforces (constructors copy the parent tenant).
fact TenantScoping {
  all e : JournalEntry | e.owner = e.period.owner
  all l : JournalLine | l.owner = l.entry.owner
  all s : ExternalSyncRecord | s.owner = s.entry.owner
}

// Given the enforced scoping, no cross-tenant reference can exist.
// (covers ACC-TENANT-001#must[0], #must[1], #must[2])
assert TenantIsolation {
  no e : JournalEntry | e.owner != e.period.owner
  no l : JournalLine | l.owner != l.entry.owner
  no s : ExternalSyncRecord | s.owner != s.entry.owner
}

check TenantIsolation for 4
`;
  return {
    backend: "alloy",
    ruleId: rule.id,
    path: "generated/alloy/AccountingTenant.als",
    text,
    scope: 4,
    generated: [{ selector: "TenantIsolation", kind: "assertion", covers: ["must[0]", "must[1]", "must[2]"] }],
  };
}
