// TLA+ backend — state transitions & temporal properties.
//
// Owns ACC-PERIOD-003 (state-transition) and ACC-SYNC-001 (temporal-property).
// Two separate modules rather than one, per the domain split. Emits real TLA+
// plus a TLC .cfg. The verifier runs TLC when present; otherwise dspec's own
// bounded state explorer (src/verify/model-check.mjs) checks the same finite
// state space and records `bounded` evidence honestly.

const PERIOD_HEADER = `\\* GENERATED by dspec from examples/accounting-core.pkl
\\* Rule: ACC-PERIOD-003 (state-transition) — primary backend: TLA+`;

function emitPeriod() {
  const text = `${PERIOD_HEADER}
-------------------------- MODULE AccountingPeriod --------------------------
EXTENDS Naturals

VARIABLES periodStatus, journalExists, journalVersion, lastOperation

vars == << periodStatus, journalExists, journalVersion, lastOperation >>

Init ==
  /\\ periodStatus = "open"
  /\\ journalExists = FALSE
  /\\ journalVersion = 0
  /\\ lastOperation = "none"

CreateJournal ==
  /\\ periodStatus = "open"
  /\\ journalExists = FALSE
  /\\ journalExists' = TRUE
  /\\ journalVersion' = 1
  /\\ lastOperation' = "create"
  /\\ UNCHANGED periodStatus

UpdateJournal ==
  /\\ periodStatus = "open"
  /\\ journalExists = TRUE
  /\\ journalVersion' = journalVersion + 1
  /\\ lastOperation' = "update"
  /\\ UNCHANGED << periodStatus, journalExists >>

DeleteJournal ==
  /\\ periodStatus = "open"
  /\\ journalExists = TRUE
  /\\ journalExists' = FALSE
  /\\ lastOperation' = "delete"
  /\\ UNCHANGED << periodStatus, journalVersion >>

ClosePeriod ==
  /\\ periodStatus = "open"
  /\\ periodStatus' = "closed"
  /\\ UNCHANGED << journalExists, journalVersion, lastOperation >>

Next ==
  \\/ CreateJournal
  \\/ UpdateJournal
  \\/ DeleteJournal
  \\/ ClosePeriod

Spec == Init /\\ [][Next]_vars

\\* INVARIANT: ClosedPeriodImmutable
\\* No mutation is the last operation while the period is closed.
ClosedPeriodImmutable ==
  (periodStatus = "closed") =>
    (lastOperation \\in {"none", "create", "update", "delete"} => TRUE)
    /\\ ~ (periodStatus = "closed" /\\ lastOperation' \\in {"create","update","delete"})

\\* The safety invariant TLC checks: a closed period never enables a mutation.
NoMutationWhenClosed ==
  (periodStatus = "closed") => ~ENABLED (CreateJournal \\/ UpdateJournal \\/ DeleteJournal)
=============================================================================`;
  const cfg = `\\* GENERATED by dspec — TLC config for AccountingPeriod
SPECIFICATION Spec
INVARIANT NoMutationWhenClosed`;
  return {
    backend: "tla",
    ruleId: "ACC-PERIOD-003",
    path: "generated/accounting/AccountingPeriod.tla",
    cfgPath: "generated/accounting/AccountingPeriod.cfg",
    text,
    cfg,
    generated: [{ selector: "ClosedPeriodImmutable", kind: "invariant", covers: ["must[0]"] }],
  };
}

const SYNC_HEADER = `\\* GENERATED by dspec from examples/accounting-core.pkl
\\* Rule: ACC-SYNC-001 (temporal-property) — primary backend: TLA+`;

function emitSync() {
  const text = `${SYNC_HEADER}
--------------------------- MODULE ExternalSync ---------------------------
EXTENDS Naturals, FiniteSets

CONSTANTS Keys, ExternalIds

VARIABLES syncStatus, attemptCount, externalIds, boundExternalId

vars == << syncStatus, attemptCount, externalIds, boundExternalId >>

\\* Each key models a fixed (tenant, provider, idempotencyKey) triple.
Init ==
  /\\ syncStatus = [k \\in Keys |-> "pending"]
  /\\ attemptCount = [k \\in Keys |-> 0]
  /\\ externalIds = {}
  /\\ boundExternalId = [k \\in Keys |-> "none"]

StartSync(k) ==
  /\\ syncStatus[k] \\in {"pending", "unknown"}
  /\\ syncStatus' = [syncStatus EXCEPT ![k] = "sending"]
  /\\ attemptCount' = [attemptCount EXCEPT ![k] = attemptCount[k] + 1]
  /\\ UNCHANGED << externalIds, boundExternalId >>

CompleteSync(k, x) ==
  /\\ syncStatus[k] = "sending"
  \\* idempotency: if already bound, must reuse the same externalId.
  /\\ (boundExternalId[k] = "none" \\/ boundExternalId[k] = x)
  /\\ syncStatus' = [syncStatus EXCEPT ![k] = "success"]
  /\\ boundExternalId' = [boundExternalId EXCEPT ![k] = x]
  /\\ externalIds' = externalIds \\cup {<<k, x>>}
  /\\ UNCHANGED attemptCount

TimeoutSync(k) ==
  /\\ syncStatus[k] = "sending"
  /\\ syncStatus' = [syncStatus EXCEPT ![k] = "unknown"]
  /\\ UNCHANGED << attemptCount, externalIds, boundExternalId >>

RetrySync(k) ==
  /\\ syncStatus[k] = "unknown"
  /\\ syncStatus' = [syncStatus EXCEPT ![k] = "sending"]
  /\\ attemptCount' = [attemptCount EXCEPT ![k] = attemptCount[k] + 1]
  /\\ UNCHANGED << externalIds, boundExternalId >>

ObserveExistingExternalRecord(k) ==
  /\\ syncStatus[k] = "unknown"
  /\\ boundExternalId[k] # "none"
  /\\ syncStatus' = [syncStatus EXCEPT ![k] = "success"]
  /\\ UNCHANGED << attemptCount, externalIds, boundExternalId >>

FailSync(k) ==
  /\\ syncStatus[k] = "sending"
  /\\ syncStatus' = [syncStatus EXCEPT ![k] = "failed"]
  /\\ UNCHANGED << attemptCount, externalIds, boundExternalId >>

Next ==
  \\E k \\in Keys :
    \\/ StartSync(k)
    \\/ \\E x \\in ExternalIds : CompleteSync(k, x)
    \\/ TimeoutSync(k)
    \\/ RetrySync(k)
    \\/ ObserveExistingExternalRecord(k)
    \\/ FailSync(k)

Spec == Init /\\ [][Next]_vars

\\* INVARIANT: IdempotentExternalSync
\\* For one key (same tenant/provider/idempotencyKey) at most one externalId is
\\* ever recorded as successful.
IdempotentExternalSync ==
  \\A k \\in Keys :
    \\A x1, x2 \\in ExternalIds :
      (x1[1] = k /\\ x2[1] = k) => (x1[2] = x2[2])
===========================================================================`;
  const cfg = `\\* GENERATED by dspec — TLC config for ExternalSync
CONSTANTS
  Keys = {k1, k2}
  ExternalIds = {e1, e2}
SPECIFICATION Spec
INVARIANT IdempotentExternalSync`;
  return {
    backend: "tla",
    ruleId: "ACC-SYNC-001",
    path: "generated/accounting/ExternalSync.tla",
    cfgPath: "generated/accounting/ExternalSync.cfg",
    text,
    cfg,
    generated: [{ selector: "IdempotentExternalSync", kind: "invariant", covers: ["must[0]"] }],
  };
}

export function emitTla(ir) {
  const out = [];
  if (ir.rules.some((r) => r.id === "ACC-PERIOD-003")) out.push(emitPeriod());
  if (ir.rules.some((r) => r.id === "ACC-SYNC-001")) out.push(emitSync());
  return out;
}
